export const breeds = [
    'Abyssinian',
    'American Bobtail',
    'American Bobtail SH',
    'American Curl',
    'American Curl LH',
    'American Shorthair',
    'American Wirehair',
    'Balinese',
    'Bengal',
    'Birman',
    'Bombay',
    'British Longhair',
    'British Shorthair',
    'Burmese',
    'Chartreux',
    'Cornish Rex',
    'Cymric',
    'Devon Rex',
    'Egyptian Mau',
    'Exotic Shorthair',
    'Havana',
    'Himalayan',
    'Japanese Bobtail',
    'Japanese Bobtail LH',
    'Korat',
    'LaPerm',
    'LaPerm Shorthair',
    'Maine Coon',
    'Manx',
    'Munchkin',
    'Munchkin Longhair',
    'Nebelung',
    'Norwegian Forest',
    'Ocicat',
    'Oriental Longhair',
    'Oriental Shorthair',
    'Persian',
    'Peterbald',
    'Pixiebob',
    'Pixiebob Longhair',
    'Ragdoll',
    'Russian Blue',
    'Scottish Fold',
    'Scottish Fold LH',
    'Selkirk Rex',
    'Selkirk Rex Longhair',
    'Siamese',
    'Siberian',
    'Singapura',
    'Snowshoe',
    'Somali',
    'Sphynx',
    'Tonkinese',
    'Toyger',
    'Turkish Angora',
    'Turkish Van',
    'Donskoy',
    'Highlander',
    'Highlander Shorthair',
    'Kurilian Bobtail',
    'Kurilian Bobtail LH',
    'Minskin',
    'Ojos Azules',
    'Ojos Azules Longhair',
    'Serengeti',
    'Sokoke',
    'Chausie',
    'Savannah',
    'Thai',
    'Tabby',
]